# Generated by Django 5.2.4 on 2025-08-26 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0003_remove_notification_related_comment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                ("content", models.TextField(verbose_name="Nội dung")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Chờ xử lý"), ("PROCESSED", "Đã xử lý")],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày xử lý"
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, verbose_name="Ghi chú admin"),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="requests_processed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người xử lý",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="requests_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người gửi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yêu cầu",
                "verbose_name_plural": "Yêu cầu",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="interaction_status_e5b471_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="interaction_user_id_1b55e9_idx",
                    ),
                ],
            },
        ),
    ]
