# Generated by Django 5.2.4 on 2025-08-26 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0006_novel_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("m", "Nam"), ("f", "Nữ"), ("o", "Khác")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("m", "Nam"), ("f", "Nữ"), ("o", "Khác")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ArtistRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("pen_name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("deathday", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("m", "Nam"), ("f", "Nữ"), ("o", "Khác")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("image_url", models.TextField(blank=True, null=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("d", "DRAFT"),
                            ("p", "PENDING"),
                            ("a", "APPROVED"),
                            ("r", "REJECTED"),
                        ],
                        db_index=True,
                        default="p",
                        max_length=1,
                    ),
                ),
                ("rejected_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_artist_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_artist",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_request",
                        to="novels.artist",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Artist Request",
                "verbose_name_plural": "Artist Requests",
            },
        ),
        migrations.AddField(
            model_name="novel",
            name="pending_artist_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="novels",
                to="novels.artistrequest",
            ),
        ),
        migrations.CreateModel(
            name="AuthorRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("pen_name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("deathday", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("m", "Nam"), ("f", "Nữ"), ("o", "Khác")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("image_url", models.TextField(blank=True, null=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("d", "DRAFT"),
                            ("p", "PENDING"),
                            ("a", "APPROVED"),
                            ("r", "REJECTED"),
                        ],
                        db_index=True,
                        default="p",
                        max_length=1,
                    ),
                ),
                ("rejected_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_author_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_author",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_request",
                        to="novels.author",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Author Request",
                "verbose_name_plural": "Author Requests",
            },
        ),
        migrations.AddField(
            model_name="novel",
            name="pending_author_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="novels",
                to="novels.authorrequest",
            ),
        ),
        migrations.AddIndex(
            model_name="artistrequest",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="novels_arti_created_54fed2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="artistrequest",
            index=models.Index(
                fields=["approval_status", "-created_at"],
                name="novels_arti_approva_cd08fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="artistrequest",
            index=models.Index(fields=["name"], name="novels_arti_name_22aeeb_idx"),
        ),
        migrations.AddIndex(
            model_name="authorrequest",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="novels_auth_created_cd735d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="authorrequest",
            index=models.Index(
                fields=["approval_status", "-created_at"],
                name="novels_auth_approva_7cfbe0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="authorrequest",
            index=models.Index(fields=["name"], name="novels_auth_name_559924_idx"),
        ),
    ]
